# Generated by Django 5.0.14 on 2026-06-27 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Текст метки')),
                ('color', models.CharField(choices=[('pine', 'Янтарный (Хит)'), ('forest', 'Зелёный (Выгодно)'), ('dark', 'Тёмный (Рекомендуем)'), ('red', 'Красный (Скидка/Заканчивается)')], default='pine', max_length=10, verbose_name='Цвет')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Метка товара',
                'verbose_name_plural': 'Метки товаров',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Название')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=140, unique=True, verbose_name='Адрес (slug)')),
                ('description', models.CharField(blank=True, help_text='Подсказка под названием в каталоге', max_length=200, verbose_name='Короткое описание')),
                ('image', models.ImageField(blank=True, upload_to='categories/', verbose_name='Фото категории')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Показывать на сайте')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='catalog.category', verbose_name='Родительская категория')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Наименование')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=220, unique=True, verbose_name='Адрес (slug)')),
                ('sku', models.CharField(blank=True, max_length=40, verbose_name='Артикул')),
                ('species', models.CharField(choices=[('pine_spruce', 'Сосна / ель'), ('linden', 'Липа'), ('larch', 'Лиственница'), ('other', 'Другое')], default='pine_spruce', max_length=20, verbose_name='Порода')),
                ('grade', models.CharField(blank=True, max_length=60, verbose_name='Сорт')),
                ('standard', models.CharField(blank=True, help_text='ГОСТ / ТУ', max_length=60, verbose_name='Стандарт')),
                ('thickness', models.PositiveIntegerField(blank=True, null=True, verbose_name='Толщина, мм')),
                ('width', models.PositiveIntegerField(blank=True, null=True, verbose_name='Ширина, мм')),
                ('length', models.PositiveIntegerField(blank=True, null=True, verbose_name='Длина, мм')),
                ('size_text', models.CharField(blank=True, help_text='Если размер нестандартный, напр. «15 × 90 × 1–3 м»', max_length=80, verbose_name='Размер (текстом)')),
                ('unit', models.CharField(choices=[('m3', '₽ / м³'), ('m2', '₽ / м²'), ('pc', '₽ / шт'), ('rm', '₽ / пог.м')], default='m3', max_length=4, verbose_name='Единица цены')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('old_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Старая цена (для скидки)')),
                ('in_stock', models.BooleanField(default=True, help_text='Снимите галочку — будет «Под заказ»', verbose_name='В наличии')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_popular', models.BooleanField(default=False, verbose_name='Показывать в «Популярном»')),
                ('is_active', models.BooleanField(default=True, verbose_name='Показывать на сайте')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Добавлен')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Изменён')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.category', verbose_name='Категория')),
                ('labels', models.ManyToManyField(blank=True, related_name='products', to='catalog.label', verbose_name='Метки')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/', verbose_name='Фото')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Фото товара',
                'verbose_name_plural': 'Фото товаров',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=80, verbose_name='Имя')),
                ('city', models.CharField(blank=True, max_length=80, verbose_name='Город')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '★'), (2, '★★'), (3, '★★★'), (4, '★★★★'), (5, '★★★★★')], default=5, verbose_name='Оценка')),
                ('text', models.TextField(verbose_name='Текст отзыва')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Одобрен (опубликован)')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('product', models.ForeignKey(blank=True, help_text='Пусто — отзыв о компании в целом', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='catalog.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'ordering': ['-created'],
            },
        ),
    ]
