# Generated by Django 5.0.14 on 2026-06-29 23:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.CharField(blank=True, max_length=200, verbose_name='Короткое описание'),
        ),
        migrations.AlterField(
            model_name='label',
            name='color',
            field=models.CharField(choices=[('pine', 'Янтарный'), ('forest', 'Зелёный'), ('dark', 'Тёмный'), ('red', 'Красный')], default='pine', max_length=10, verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='product',
            name='in_stock',
            field=models.BooleanField(default=True, verbose_name='В наличии'),
        ),
        migrations.AlterField(
            model_name='product',
            name='old_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Старая цена'),
        ),
        migrations.AlterField(
            model_name='product',
            name='size_text',
            field=models.CharField(blank=True, max_length=80, verbose_name='Размер (текстом)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='standard',
            field=models.CharField(blank=True, max_length=60, verbose_name='Стандарт'),
        ),
        migrations.AlterField(
            model_name='review',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='catalog.product', verbose_name='Товар'),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=5, verbose_name='Оценка'),
        ),
    ]
