# Generated by Django 5.0.14 on 2026-07-02 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_category_description_alter_label_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='admin_seen',
            field=models.BooleanField(default=False, verbose_name='Просмотрено администратором'),
        ),
    ]
