# Generated by Django 5.0.14 on 2026-07-08 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_review_admin_seen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('m3', '₽ / м³'), ('m2', '₽ / м²'), ('pc', '₽ / шт'), ('rm', '₽ / пог.м'), ('sheet', '₽ / лист')], default='m3', max_length=6, verbose_name='Единица цены'),
        ),
    ]
