# Generated by Django 5.0.14 on 2026-06-27 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=250, verbose_name='Вопрос')),
                ('answer', models.TextField(verbose_name='Ответ')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Показывать')),
            ],
            options={
                'verbose_name': 'Вопрос-ответ (FAQ)',
                'verbose_name_plural': 'Частые вопросы (FAQ)',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='ЛЕСПРОФБАЗА', max_length=120, verbose_name='Название')),
                ('slogan', models.CharField(default='Довольный клиент — наша задача!', max_length=160, verbose_name='Девиз')),
                ('phone', models.CharField(blank=True, max_length=40, verbose_name='Телефон')),
                ('phone2', models.CharField(blank=True, max_length=40, verbose_name='Запасной телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('address', models.CharField(blank=True, max_length=300, verbose_name='Адрес / самовывоз')),
                ('hours', models.CharField(blank=True, default='Ежедневно, 8:00–20:00', max_length=120, verbose_name='Часы работы')),
                ('whatsapp', models.CharField(blank=True, max_length=200, verbose_name='WhatsApp (ссылка/номер)')),
                ('telegram', models.CharField(blank=True, max_length=200, verbose_name='Telegram (ссылка)')),
                ('max_link', models.CharField(blank=True, max_length=200, verbose_name='MAX (ссылка)')),
                ('instagram', models.CharField(blank=True, max_length=200, verbose_name='Instagram (ссылка)')),
                ('tg_bot', models.CharField(blank=True, max_length=200, verbose_name='Telegram-бот (ссылка)')),
                ('free_delivery_m3', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Бесплатная доставка от, м³')),
                ('map_embed', models.TextField(blank=True, verbose_name='Код карты (iframe Яндекс/OSM)')),
                ('yandex_maps_url', models.CharField(blank=True, max_length=300, verbose_name='Ссылка «Открыть в Яндекс.Картах»')),
                ('show_product_reviews', models.BooleanField(default=True, verbose_name='Показывать отзывы на товары')),
                ('show_product_rating', models.BooleanField(default=True, verbose_name='Показывать рейтинг товаров')),
                ('show_company_reviews', models.BooleanField(default=False, verbose_name='Показывать отзывы о компании')),
            ],
            options={
                'verbose_name': 'Настройки сайта',
                'verbose_name_plural': 'Настройки сайта',
            },
        ),
        migrations.CreateModel(
            name='StaticPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='Напр.: o-kompanii, dostavka-i-oplata, dlya-yurlic', max_length=80, unique=True, verbose_name='Адрес (slug)')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('body', models.TextField(blank=True, verbose_name='Содержимое (HTML)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Показывать')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Изменена')),
            ],
            options={
                'verbose_name': 'Страница',
                'verbose_name_plural': 'Страницы (О компании, Доставка и т.д.)',
            },
        ),
    ]
