# Generated by Django 5.0.14 on 2026-07-08 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='catalog_version',
            field=models.CharField(blank=True, default='', max_length=40, verbose_name='Версия каталога (служебное)'),
        ),
    ]
