# Generated by Django 5.0.14 on 2026-06-27 17:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('callback', 'Заказать звонок'), ('quick', 'Быстрый заказ'), ('consult', 'Консультация / подбор')], default='callback', max_length=12, verbose_name='Тип')),
                ('name', models.CharField(blank=True, max_length=120, verbose_name='Имя')),
                ('phone', models.CharField(max_length=40, verbose_name='Телефон')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('processed', models.BooleanField(default=False, verbose_name='Обработана')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки (звонки, быстрый заказ)',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Имя')),
                ('phone', models.CharField(max_length=40, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('receive', models.CharField(choices=[('pickup', 'Самовывоз'), ('delivery', 'Доставка')], default='pickup', max_length=10, verbose_name='Получение')),
                ('address', models.CharField(blank=True, max_length=300, verbose_name='Адрес доставки')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Сумма (предв.)')),
                ('status', models.CharField(choices=[('new', 'Новая'), ('in_progress', 'В работе'), ('done', 'Закрыта')], default='new', max_length=12, verbose_name='Статус')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Наименование')),
                ('size_text', models.CharField(blank=True, max_length=80, verbose_name='Размер')),
                ('unit', models.CharField(blank=True, max_length=10, verbose_name='Единица')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('qty', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('line_total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Сумма строки')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Позиция заказа',
                'verbose_name_plural': 'Позиции заказа',
            },
        ),
    ]
