# Generated by Django 5.0.14 on 2026-07-02 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'На рассмотрении'), ('in_progress', 'В работе'), ('shipping', 'Едет к вам'), ('done', 'Доставлен')], default='new', max_length=12, verbose_name='Статус'),
        ),
    ]
