# Generated by Django 5.0.14 on 2026-07-02 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='admin_seen',
            field=models.BooleanField(default=False, verbose_name='Просмотрено администратором'),
        ),
        migrations.AddField(
            model_name='order',
            name='admin_seen',
            field=models.BooleanField(default=False, verbose_name='Просмотрено администратором'),
        ),
    ]
